// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgsi_D8S5ffFI-9M339qbEtZ3lTgcPYs8',
    appId: '1:219102363756:android:c47253dba69cdf237a1849',
    messagingSenderId: '219102363756',
    projectId: 'smartmeasurepro-9eac6',
    storageBucket: 'smartmeasurepro-9eac6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCTZRuuK2XGk22t7Rr6FYxo2BOHcQ57co',
    appId: '1:219102363756:ios:1281cc7ce000876b7a1849',
    messagingSenderId: '219102363756',
    projectId: 'smartmeasurepro-9eac6',
    storageBucket: 'smartmeasurepro-9eac6.firebasestorage.app',
    iosClientId: '219102363756-i6vcpois559u9fnjs7vkbp4p1hgvksb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartMeasurePro',
  );
}
